# Etapa de compilación
FROM node:20-alpine as build-stage
WORKDIR /app
COPY reto2-frontend/package*.json ./
RUN npm install
COPY reto2-frontend/ .
RUN npm run build

# Etapa de producción
FROM httpd:alpine as production-stage

# Copiar los archivos compilados
COPY --from=build-stage /app/dist /usr/local/apache2/htdocs/

# Copiar el archivo .htaccess para el enrutamiento de SPA
COPY .htaccess /usr/local/apache2/htdocs/

# Habilitar mod_rewrite en el archivo de configuración de Apache
RUN sed -i '/LoadModule rewrite_module/s/^#//' /usr/local/apache2/conf/httpd.conf && \
    sed -i 's/AllowOverride None/AllowOverride All/g' /usr/local/apache2/conf/httpd.conf

EXPOSE 80

